Venho através deste link para solicitar o envio de um currículo para o o òtimos profissionais que foi penalizados durantes esses anos em trabalhos sem merecer e nem ter a oportunidade de estar a desenvolver mais ainda as suas abilidades profissional. Eu não sei o que vai acontecer mas não vou deixar de falar e nem sei o que essas pessoas ficam fazendo com tanta mentiras. Eu Sônia Aparecida Gonçalves Dos Reis cadastrei para trabalhar na produção da Mercedes Bens de Juiz de Fora Mg isso foi já faz a vários anos atrás e nem se quer eles responderam e nem deram retorno nunca. Tenho condições plena de efetuar o trabalho de produção e qual dúvidas pode solicitar as informações em Portugal PT no Grande Hotel Das Caldas da Felgueira onde trabalhei quase seis meses e sai pois não é o quero e sim para conhecimentos. O que peço que os setores dos Recursos Humanos não jogues foram os currículos que recebem, pois sou testemunha VIVA de enviar vários Curriculos via email e Correios para o Brasil e USA para às empresas a vários anos atrás e nunca tive oportunidade e nem retorno. Lembro como fosse hoje meu esposo José Aparecido dos Reis joseapdosreis@hotmail.com ter trabalhado na própria empresa e nunca foi possível ter a oportunidade de crescimento na empresa MERCEDES BENZ e nem se quer ofereceram alguma OPORTUNIDADES  OU Cargos que possa estar na condições e qualidade de vida de acordo com sua capacidade que foi desenvolvida durante todos esses anos. Qualquer coisa, estamos nestes e-mails, joseapdosreis@hotmail.com e dosreisjoseaparecido62@gmail.com .Sem dúvida, temos condições para exercer qualquer atividade de acordo com a nossa capacidade e vontade de aprender.  SÔNIA APARECIDA GONÇALVES DOS REIS e JOSE APARECIDO DOS REIS(351)914 162 674. Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
